### ISSUE TITLE
Issues running the tool

### ISSUE THREAD

**Issue by stevetsa** [SamSamhuns/predemic#23]
I received an warning for importing joblib directly when I ran this tool as instructed.  When I did that, I got another error -

" File "svm.py", line 35, in <module>
    main()
  File "svm.py", line 29, in main
    C = train('data.csv')
  File "svm.py", line 23, in train
    print(accuracy_score(y_val, y_pred))
NameError: name 'accuracy_score' is not defined"

**Comment by SamSamhuns** [comment]
The issue should be resolved now. All unresolved name references have been removed and the joblib imports fixed.
